<?php
$helper = Mage::helper('fresh_local');
$_product = $this->getProduct();
?>

<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<div class="modal-body">
			<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><i class="ic-icn-x"></i></button>
				<form action="<?php echo $this->getUrl('freshlocal/checkout_cart/ajaxadd', array('id' => $_product->getId(), '_secure' => $this->_isSecure())) //$this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
				<?php echo $this->getBlockHtml('formkey') ?>
				<div class="no-display">
					<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
					<input type="hidden" name="related_product" id="related-products-field" value="" />
				</div>
				<div class="row">
					<div class="col-md-6">
						  <div class="product-overview__img-box">
							<img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(230, 230); ?>" 
								title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" 
								alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-overview__img">
						  </div>
					</div>
					<div class="col-md-6">
						<h3 class="product-overview__title"><?php echo $_product->getName(); ?></h3>
						<span class="product-overview__info"><?php echo $_product->getShortDescription(); ?></span>
						<span class="product-overview__price"><?php echo $this->getPriceHtml($_product); ?></span>
						<div class="product-overview__btn-wrap">
							<?php /*<button type="button" class="product-overview__btn"><span><strong>1</strong> in Cart</span></button>*/ ?>
							<?php echo $this->getChildHtml('addtocart') ?>
							<div class="product-overview__control">
								<button class="product-overview__control__btn product-overview__control__btn--plus"><i class="ic-icn-plus-bold"></i></button>
								<button class="product-overview__control__btn product-overview__control__btn--minus"><i class="ic-icn-minus-bold"></i></button>
							</div>
						</div>
						<ul class="product-overview__list">
							<?php echo $this->getChildHtml('addto') ?>
							<li><a href="<?php echo $helper->getFavoritesUrl($_product) ?>"><i class="ic-icn-star"></i><span>Favorite</span></a></li>
							<li><a href=""><i class="ic-icn-receipt"></i><span>Add to List</span></a></li>
							<li><a href=""><i class="ic-icn-flag"></i><span>Incorrect info?</span></a></li>
						</ul>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>







<div class="product-essential">
	<form action="<?php echo $this->getUrl('freshlocal/checkout_cart/ajaxadd', array('id' => $_product->getId(), '_secure' => $this->_isSecure())) //$this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<?php echo $this->getBlockHtml('formkey') ?>
	<div class="no-display">
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
		<input type="hidden" name="related_product" id="related-products-field" value="" />
	</div>
    <div class="product-img-box">
        <?php /*<a href="<?php echo $_product->getProductUrl(); ?>">*/ ?>
		<img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(230, 230); ?>"/>
        <?php //</a> ?>
    </div>

    <div class="product-shop">
        <h3 class="product-name"><?php echo $_product->getName(); ?></h3>

        <h4><?php echo $this->__('Quick Overview') ?></h4>
        <div class='short-description'><?php echo $_product->getShortDescription(); ?></div>

        <div class='divider'></div>

        <div class="col2-set">
            <div class="col-1">
                <?php echo $this->getPriceHtml($_product); ?>
            </div>
            <div class="col-2">
                <?php /*if($_product->isSaleable()): ?>
                    <button class="button" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php endif;*/ ?>
				
				<?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
            </div>
        </div>
    </div>
	
    <div class="clear"></div>
	</form>
</div>