<?php
	$helper = Mage::helper('fresh_local');
    $_item = $this->getItem();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item" xmlns="http://www.w3.org/1999/html">
	<?php if ($this->hasProductUrl()): ?>
        <?php /* <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"> */ ?>
		<a href="<?php echo $helper->getQuickViewUrl($_item->getProduct()) ?>" data-toggle="modal" data-target="#productOverview" class="product-image quick-view"><img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details">
        <p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $helper->getQuickViewUrl($_item->getProduct()) ?>" data-toggle="modal" data-target="#productOverview" class="quick-view"><?php endif; ?><?php echo $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?>
		<span class="product-info"><?php echo $this->__('Qty'); ?> <?php echo $this->getQty()?></span></p>

        <table class="info-wrapper">
            <tbody>
                <tr>
                    <?php /*<th><?php echo $this->__('Price'); ?></th>*/ ?>
                    <td>
                        <?php if ($canApplyMsrp): ?>
                            <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
                        <?php else: ?>
                            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                    <?php echo $this->__('Excl. Tax'); ?>:
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                                    <br />
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                            <?php endforeach; ?>
                                        </small>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php endif; ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                    <br /><?php echo $this->__('Incl. Tax'); ?>:
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                                    <br />
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php endif; ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                        <?php endif; //Can apply MSRP ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</li>
