<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>

<button data-toggle-btn class="header-cart__btn"><i class="ic-icn-arrow-right-small-bold"></i></button>
	<?php /*<div id="minicart-error-message" class="minicart-message"></div>
	<div id="minicart-success-message" class="minicart-message"></div>*/ ?>
	<div class="minicart-wrapper">
		<div class="minicart-wrapper__head">
			<div class="minicart-wrapper__head__icn"><i class="ic-icn-cart-filled"></i></div>
			<div class="minicart-wrapper__head__title">
				<h4><?php echo $this->__('Shopping Cart') ?></h4>
			</div>
			<div class="minicart-wrapper__head__price">
				<span>
				<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
				<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
					(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
				<?php endif; ?>
				</span>
			</div>
		</div>
		<div id="minicart-widgets">
			<div class="block-content">
				<p>Next Delivery: Today, 4pm - 5m</p>
			</div>
			<div class="free-shipp-box"><span class="text-free-shipp">Your first delivery is free!</span></div>
		</div>
		<div>
			<ul id="cart-sidebar" class="mini-products-list">
			<?php $_items = $this->getRecentItems() ?>
			<?php $countItems = count($_items); ?>
			<?php if($countItems): ?>
				<?php foreach($_items as $_item): ?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endforeach; ?>
			<?php endif; ?>
			</ul>
		</div>
	</div>
	<div class="minicart-actions">
	<?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
		<?php echo $this->getChildHtml('extra_actions') ?>
		<a href="<?php echo $this->getCheckoutUrl() ?>" class="cart-link"><?php echo $this->__('Checkout') ?>
		<span class="cart-link__price">
			<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
			<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
				(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
			<?php endif; ?>
		</span></a>
	<?php endif ?>
	</div>
	
<?php /*
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>

<div class="minicart-wrapper">

    <p class="block-subtitle">
        <?php echo $this->__('Recently added item(s)') ?>
        <a class="close skip-link-close" href="#" title="<?php echo $this->quoteEscape($this->__('Close')); ?>">&times;</a>
    </p>

    <?php $_items = $this->getRecentItems() ?>
    <?php $countItems = count($_items); ?>
    <?php if($countItems): ?>
        <div>
            <ul id="cart-sidebar" class="mini-products-list">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <script type="text/javascript">
            truncateOptions();
            decorateList('cart-sidebar', 'none-recursive');
            $j('document').ready(function() {
                var minicartOptions  = {
                    formKey:           "<?php echo $this->getFormKey();?>"
                }
                var Mini = new Minicart(minicartOptions);
                Mini.init();
            });
        </script>

        <div id="minicart-widgets">
            <?php echo $this->getChildHtml('cart_promotion') ?>
        </div>
        <div class="block-content">
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>


        <div class="minicart-actions">
            <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                <ul class="checkout-types minicart">
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <li>
                        <a title="<?php echo $this->quoteEscape($this->__('Checkout')) ?>" class="button checkout-button" href="<?php echo $this->getCheckoutUrl() ?>">
                            <?php echo $this->__('Checkout') ?>
                        </a>
                    </li>
                </ul>
            <?php endif ?>
            <a class="cart-link" href="<?php echo $this->getUrl('checkout/cart'); ?>">
                <?php echo $this->__('View Shopping Cart'); ?>
            </a>
        </div>

    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>

    <?php endif ?>
</div>
*/ ?>
