<?php /* ?>
<div class="page-title clearer">
	<h1 class="faq-title"><?php echo $this->__('Frequently Asked Questions'); ?></h1>
	<?php echo $this->getChildHtml('search-form'); ?>
</div>

<?php echo $this->getChildHtml('topics'); ?>
<?php echo $this->getChildHtml('answers');*/ ?>
       
<div class="main-container">
	<div class="main">
		<div class="col-main">
			<div class="container">
                <div class="page-title clearer">
					<?php echo $this->getChildHtml('search-form'); ?>
                </div>
                <?php echo $this->getChildHtml('topics'); ?>
                <?php echo $this->getChildHtml('answers'); ?>
			</div>
        </div>
	</div>
</div>