<div class="main-container">
	<div class="main">
		<div class="col-main">
			<div class="container">
                <div class="page-title clearer">
					<h3><?php echo $this->__('Search Results for "%s" <a href="%s">(back)</a>', $this->htmlEscape($this->getQuery()), $this->getUrl(Mage::helper('extendedfaq')->getUrl())); ?></h3>
					<?php echo $this->getChildHtml('search-form'); ?>
                </div>
                <?php echo $this->getChildHtml('topics'); ?>
                <?php echo $this->getChildHtml('answers'); ?>
			</div>
        </div>
	</div>
</div>
