<?php /*<div class="header-home">
	<div class="logo-home"><a href="<?php echo $this->getUrl('') ?>" class="logo-home__link"><img src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')) ?>" alt="<?php echo Mage::getStoreConfig('design/header/logo_alt') ?>"></a></div>
	<div class="header-home__btn-box"><a href="<?php echo Mage::getUrl('customer/account/create'); ?>" class="btn-default btn"><?php echo $this->__('Sign up') ?></a></div>
</div>*/ ?>
<div class="main-container">
	<div class="main">
		<div class="col-main">
			<div class="container">
				<div class="account-login">
					<div class="page-title">
						<h1><?php echo $this->__('hooked on fresh food?') ?></h1>
						<p class="page-title__text"><?php echo $this->__('Let`s shop!') ?></p>
					</div>
					<?php echo $this->getMessagesBlock()->toHtml() ?>
					<?php /* Extensions placeholder */ ?>
					<?php echo $this->getChildHtml('customer.form.login.extra')?>
					<form id="login-form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
						<?php echo $this->getBlockHtml('formkey'); ?>
						<div class="row">
							<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
								<div class="form-group">
									<input  type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="form-control input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Enter email or phone number')) ?>" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Enter email or phone number')) ?>" />
								</div>
								<div class="form-group">
									<input type="password" name="login[password]" class="form-control input-text required-entry validate-password" id="pass" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
								</div>
								
								<?php echo $this->getChildHtml('form.additional.info'); ?>
								<?php echo $this->getChildHtml('persistent.remember.me'); ?>
								<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
								<div class="new-users">
									<div class="buttons-set">
										<button type="submit" class="button btn btn-warning btn-block btn-md" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
										<?php echo $this->getChildHtml('fblogin') ?>
										<p class="form-text text-center"><?php echo $this->__('Forgot your password?') ?><a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Reset it') ?></a></p>
										<p class="form-text text-center"><?php echo $this->__('Don’t have an account?') ?><a href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"> <?php echo $this->__('Sign up') ?></a></p>
									</div>
								</div>
							</div>
						</div>
						
						<?php if(Mage::helper('checkout')->isContextCheckout()): ?>
							<input name="context" type="hidden" value="checkout" />
						<?php endif; ?>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('login-form', true);
//]]>
</script>

<?php /*
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content">
                    <h2><?php echo $this->__('Registered Customers') ?></h2>
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="buttons-set">
                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>*/ ?>
