<?php /*<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>*/ ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off" enctype="multipart/form-data">
    <?php /*<div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>*/ ?>
	<?php $customer = $this->getCustomer(); ?>
	<div class="row">
		<div class="col-sm-6">
			<div class="fieldset">
				<?php echo $this->getBlockHtml('formkey')?>
				<h2 class="legend">Personal information</h2>
				<div class="row">
					<div class="col-lg-10">
						<div class="user-setting">
							<div class="user-setting__ava">
								<div class="user-setting__avatar">
									<?php 
										$image = $customer->getProfileImage(); 
										if(!$image){
											$image = $this->getSkinUrl('images/user.jpg');
										} else {
											$image = Mage::getModel('fresh_local/customer_profileimage')->getProfileimageUrl($image);
										}
										
									?>
									<img src="<?php echo $image ?>" alt="User avatar" class="user-setting__ava__img" />
									
								</div>
								<input type="file" id="profile_image" name="profile_image" class="button btn-save" style="width:135px;" />
							</div>
							<div class="user-setting__fields">
								<ul class="form-list">
									<li class="fields">
										<div class="form-group">
											<input id="firstname" type="text" name="firstname" placeholder="First Name" title="First Name" class="input-text form-control required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" value="<?php echo $this->escapeHtml($customer->getFirstname()) ?>" />
										</div>
										<div class="form-group">
											<input id="lastname" type="text" name="lastname" placeholder="Last Name" title="Last Name" class="input-text required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" value="<?php echo $this->escapeHtml($customer->getLastname()) ?>" />
										</div>
										<div class="form-group">
											<input id="phone" type="text" name="phone" placeholder="Phone Number" title="Phone Number" class="input-text required-entry" value="<?php echo $this->escapeHtml($customer->getPhone()) ?>" /><span>(no spaces or dashes e.g. 08023456789)</span>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="fieldset">
				<h2 class="legend">Account information</h2>
				<ul class="form-list">
					<li>
						<div class="field-info">
							<div class="field-info__title"><span>Email</span></div>
							<div class="field-info__block">
                                <?php /*<div class="field-info__shower"><span><?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?></span></div>*/ ?>
                                <div class="field-info__editor"><!-- hidden-->
									<div class="form-group">
										<input id="email" type="text" name="email" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
									</div>
                                </div>
								<?php /*<a href="" class="field-info__link">Change</a>*/ ?>
							</div>
						</div>
					</li>
					<?php /*
					<li>
						<div class="field-info">
							<div class="field-info__title"><span>Password</span></div>
							<div class="field-info__block">
                                <div class="form-group">
									<input id="dummy" type="text" name="dummy" class="input-text no-display">
									<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
								</div>
								
								<input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
								<label for="change_password"><?php echo $this->__('Change Password') ?></label>
								
								<div class="form-group">
									<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
								</div>
								<div class="form-group">
									<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
								</div>
								
                                <div class="field-info__editor hidden">
									<ul class="form-list">
										<li>
											<input type="text" class="input-text no-display" name="dummy" id="dummy" />
											<div class="form-group">
												<input id="dummy" type="text" name="dummy" class="input-text no-display">
												<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
											</div>
											<div class="form-group">
												<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
											</div>
											<div class="form-group">
												<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
											</div>
										</li>
									</ul>
                                </div>
								
							</div>
						</div>
					</li>*/ ?>
					
					
				</ul>
				
				<input type="checkbox" name="change_password" id="change_password" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> /><?php //class="checkbox" ?>
				<label for="change_password"><?php echo $this->__('Change Password') ?></label>			
				<ul class="form-list" id="change_password_block" style="display:none;">
					<li>
						<div class="field-info">
							<div class="field-info__title"><span>Current Password</span></div>
							<div class="field-info__block">
                                <div class="field-info__editor">
									<div class="form-group">
										<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
									</div>
                                </div>
							</div>
						</div>
					</li>
					<li>
						<div class="field-info">
							<div class="field-info__title"><span>New Password</span></div>
							<div class="field-info__block">
                                <div class="field-info__editor">
									<div class="form-group">
										<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
									</div>
                                </div>
							</div>
						</div>
					</li>
					<li>
						<div class="field-info">
							<div class="field-info__title"><span>Confirm New Password</span></div>
							<div class="field-info__block">
                                <div class="field-info__editor">
									<div class="form-group">
										<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
									</div>
                                </div>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<?php $whatsapp = $customer->getWhatsappExist(); ?>
			<div class="box-social"><span class="box-social__title">Are you available on Whatsapp?</span>
				<div class="radio-line"><i class="icon-phone-circle"></i>
					<label class="radio-item"><span class="radio-item__title">yes</span>
						<span class="radio-item__btn">
							<input type="radio" name="whatsapp_exist" value="1"<?php if($whatsapp): ?> checked="checked"<?php endif; ?> /><span></span>
						</span>
					</label>
					<label class="radio-item"><span class="radio-item__title">no</span>
						<span class="radio-item__btn">
							<input type="radio" name="whatsapp_exist" value="0"<?php if(!$whatsapp): ?> checked="checked"<?php endif; ?> /><span></span>
						</span>
					</label>
				</div>
			</div>
			  <!--
			  <div class="buttons-set">
				<p class="required">* Required Fields</p>
				<p class="back-link"><a href="http://freshtodommot.com/customer/address/new/"><small>&laquo;</small>Back</a></p>
				<button type="submit" title="Save" class="button"><span><span>Save</span></span></button>
			  </div>
			  -->
		</div>
	</div>
	
    <div class="buttons-set">
        <?php /*<p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>*/ ?>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button btn-save"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    jQuery(document).ready(function($){
		$('#change_password').on('change', function(){
			var arg = $(this).prop('checked');
			if(arg){
				$('#change_password_block').show();
				$('#current_password').addClass('required-entry');
				$('#password').addClass('required-entry');
				$('#confirmation').addClass('required-entry');

			}else{
				$('#change_password_block').hide();
				$('#current_password').removeClass('required-entry');
				$('#password').removeClass('required-entry');
				$('#confirmation').removeClass('required-entry');
			}
		});
	});

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
