<?php echo $this->getChildHtml('default.header'); ?>
<div class="main-container">
	<div class="main">
		<div class="col-main">
			<div class="container">
				<div class="account-login">
					<div class="page-title">
						<h1><?php echo $this->__('Forgot your password?') ?></h1>
						<p class="page-title__text"><?php echo $this->__('We`ll send you a link to reset your password') ?></p>
					</div>
					<?php echo $this->getMessagesBlock()->toHtml() ?>
					<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
						<?php echo $this->getBlockHtml('formkey'); ?>
						<div class="row">
							<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
								<div class="form-group">
									<input type="text" name="email" alt="email" id="email_address" class="form-control input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Enter Email address')) ?>" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Enter Email address')) ?>" />
								</div>
								<?php echo $this->getChildHtml('form.additional.info'); ?>
								<div class="new-users">
									<div class="buttons-set">
										<button type="submit" class="button btn btn-warning btn-block btn-md" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset password')) ?>" name="send" id="send2"><span><span><?php echo Mage::helper('core')->quoteEscape($this->__('Reset password')) ?></span></span></button>
										<p class="form-text text-center"><?php echo $this->__('Do you already have an account?') ?><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"> <?php echo $this->__('Sign in') ?></a></p>
										<p class="form-text text-center"><?php echo $this->__('Don’t have an account?') ?><a href="<?php echo Mage::getUrl('customer/account/create'); ?>"> <?php echo $this->__('Sign up') ?></a></p>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>

<?php /*
<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('!/!/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
*/ ?>