<?php echo $this->getChildHtml('default.header'); ?>
<div class="main-container">
	<div class="main">
		<div class="col-main">
			<div class="container">
				<div class="account-login">
					<div class="page-title">
						<h1><?php echo $this->__('Forgot your password?') ?></h1>
						<?php /*<p class="page-title__text"><?php echo $this->__('We`ll send you a link to reset your password') ?></p>*/ ?>
					</div>
					<?php echo $this->getMessagesBlock()->toHtml(); ?>
					<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
						<?php echo $this->getBlockHtml('formkey'); ?>
						<div class="row">
							<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
								<div class="form-group">
									<input type="password" class="form-control password-check input-text required-entry validate-password" name="password" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" />
								</div>
								<div class="form-group">
									<input type="password" class="form-control input-text required-entry validate-cpassword" name="confirmation" id="confirmation" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" />
								</div>
								<div class="new-users">
									<div class="buttons-set">										
										<button type="submit" class="button btn btn-warning btn-block btn-md" title=""<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" name="send" id="send2"><span><span><?php echo Mage::helper('core')->quoteEscape($this->__('Reset password')) ?></span></span></button>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
<?php /*
<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('!/!/resetpasswordpost'); ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top: 70px;">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>*/ ?>
