<?php  echo "asdasd";
foreach ($types as $type) {
            if ( $messages = $this->getMessages($type) ) {
                if ( !$html ) {
                    $html .= '<div class="messages">';
                }
                $html .= '<div class="alert alert-' . $type . '" role="alert">';
                $html .= '<ul>';

                foreach ( $messages as $message ) {
                    $html.= '<li>';
                    $html.= $message->getText();
                    $html.= '</li>';
                }
                $html .= '</ul>';
                $html .= '</div>';
            }
        }
        if ( $html) {
            $html .= '</div>';
        }
?>
