<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
//]]>
</script>


<form action="" id="co-payment-form">
	<div class="page-header text-center">
		<ul class="page-header__steps">
			<li><span>Delivery</span></li>
			<li><a href="#" onclick="return false;">Payment</a></li>
		</ul>
	</div>
<?php /*<div class="container-fluid">
		<div class="payment-box">
			<div class="payment-box__row">
				<div class="payment-box__title pt-8">Payment options</div>
				<div class="payment-box__content">
                    <label class="radio-item">
						<span class="radio-item__btn"><input type="radio" name="payment"><span></span></span>
						<span class="radio-item__title"><img src="images/quiсk.png" alt=""></span>
					</label>
                    <button class="btn btn-success btn-xs sm-min-pull-right text-lc">Choose another payment option</button>
				</div>
			</div>
			<div class="payment-box__row">
				<div class="payment-box__title pt-8">Subtotal</div>
                  <div class="payment-box__content"><strong class="payment-box__price">&#8358;90.71</strong></div>
			</div>
			<div class="payment-box__row">
				<div class="payment-box__title pt-8">Delivery</div>
				<div class="payment-box__content"><strong class="payment-box__price">&#8358;11.98</strong></div>
			</div>
			<div class="payment-box__row">
                  <div class="total-box">
                    <div class="total-box__save"><span class="total-box__save-price">You saved:<strong> &#8358;50</strong></span></div>
                    <div class="total-box__total"><span class="total-box__new-price">Total:<strong> &#8358;52.69</strong></span><span class="total-box__old-price">&#8358;102.69</span></div>
                  </div>
			</div>
			<div class="payment-box__btn-wrap">
				<button class="payment-box__btn pull-left btn btn-default">Back</button>
				<button class="payment-box__btn pull-right btn btn-success">Submit order</button>
				<button class="payment-box__btn sm-min-pull-right btn btn-promo">Use promo code or caviar points</button>
			</div>
		</div>
	</div> */ ?>
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
	<?php echo $this->getChildHtml('checkout.onepage.review') ?>
</form>
<?php /* <div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" /></div>
</div>
<div class="buttons-set" id="payment-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div> */ ?>
<?php /*<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>*/ ?>
