<?php $user = $this->helper('fblogin')->getFbUser()?>
<?php /*<div id="form-loginfb" style="text-align:center">
	<?php if($user){?>
		<?php if($this->isShowAvatar()){?>
			<img src="http://graph.facebook.com/<?php echo $user['id'] ?>/picture" />
		<?php }?>
		<p><?php echo $this->getConnectedTemplate() ?></p>
	<?php }else{?>
		<?php echo $this->getNotConnectedTemplate() ?>
	<?php }?>
</div>*/ ?>
<?php $action = '';
if(!$user || !$user['email']){
	$action = 'onclick="login();return false;" href="#"';
}else{
	$action = 'onclick="window.location.href = \''. $this->getFbloginUrl() .'\';"';
} 

$text = $this->__('Sign in with');
if(Mage::app()->getRequest()->getActionName() == 'create'){
	$text = $this->__('Sign up with');
}
?>


<p class="form-text text-center">or</p><a <?php echo $action ?> class="btn btn-block btn-md btn-facebook"><i class="icon-facebook-white"></i><span><?php echo $text ?></span><strong> <?php echo $this->__('Facebook') ?></strong></a>

<script src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">
<?php if (!$user) { ?>
var newwindow;
var intId;
function login(){
	var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
	var	 screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
	var	 outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
	var	 outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
	var	 width    = 500;
	var	 height   = 270;
	var	 left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
	var	 top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
	var	 features = (
			'width=' + width +
			',height=' + height +
			',left=' + left +
			',top=' + top
		  );

	newwindow=window.open('<?php echo $this->getFbLoginButtonUrl() ?>','Login_by_facebook',features);

	if (window.focus) {
		newwindow.focus()
	}
	return false;
}
<?php } ?>
</script>