
<?php /* <div class="page-title title-buttons">
    <h1><?php echo $this->__('Address Book') ?></h1>
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Address')) ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
</div> */ ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>



	<div class="row">
		<div class="col-sm-7 col-sm-push-5">
			<div class="account-list">
				<?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
					<?php $_address = Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses); ?>
					<div class="account-list__item">
						<h3 class="account-list__item__title"><?php echo $_address->getAddressLabel() ?></h3>
						<a href="<?php echo $this->getAddressEditUrl($_address) ?>" 
							class="account-list__item__title__link">
							<?php echo $this->__('Edit') ?>
						</a>
						<p><?php echo $this->helper('fresh_local/customer_data')->getAddressHtml($_address) ?></p>
					</div>
				<?php else: ?>
					<div class="account-list__item">
						<h3 class="account-list__item__title"><?php echo $this->__('Default Address') ?></h3>
						<p><?php echo $this->__('You have no default billing address in your address book.') ?></p>
					</div>
				<?php endif ?>
				
				
				<?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
					<?php foreach($_pAddsses as $_address): 
						//$_address = Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_address->getId());
					?>					
					<div class="account-list__item">
						<h3 class="account-list__item__title"><?php echo $_address->getAddressLabel() //echo $_address->getAddressLabel() ?></h3>
						<a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>" 
							class="account-list__item__title__link">
							<?php echo $this->__('Edit') ?>
						</a> 
						<?php /*<span class="separator">|</span> <a href="#" class="account-list__item__title__link" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>*/ ?>
						
						<?php /*<p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>*/ ?>
						<?php /*<p>
						<a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> 
						<a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>
						</p>*/ ?>
						
						<p><?php echo $this->helper('fresh_local/customer_data')->getAddressHtml($_address) ?></p>
					</div>
					<?php endforeach; ?>
				<?php else: ?>
					<div class="account-list__item">
						<h3 class="account-list__item__title"><?php echo $this->__('Other Address') ?></h3>
						<p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
					</div>
				<?php endif ?>
			</div>
		</div>
		<div class="col-sm-5 col-sm-pull-7">
			<?php /*
			<div class="account-new-btn-wrap">
			  <button type="button" class="account-new-btn"><i class="ic-icn-plus-bold"></i><span>New Address</span></button>
			</div>
			<div class="account-new-form">
				<form id="form-validate" action="http://freshtodommot.com/customer/address/formPost/" method="post">
					<div class="form-group">
						<div class="form-group__title"><span>Label</span></div>
						<div class="form-group__container">
							<input type="text" name="success_url" value="" placeholder="e.g Home" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<div class="form-group__title"><span>Address Type</span></div>
						<div class="form-group__container">
							<label class="radio-item"><span class="radio-item__btn">
								<input type="radio" name="whatsapp"><span></span></span><span class="radio-item__title">Residential</span></label>
							<label class="radio-item"><span class="radio-item__btn">
								<input type="radio" name="whatsapp"><span></span></span><span class="radio-item__title">Non-residential</span></label>
						</div>
					</div>
					<div class="form-group">
						<div class="form-group__title"><span>Flat №</span></div>
						<div class="form-group__container">
							<input type="text" name="success_url" placeholder="(optional) e.g Flat 15" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<div class="form-group__title"><span>Street Address</span></div>
						<div class="form-group__container">
							<input type="text" name="success_url" placeholder="e.g. 8, Ibeju Lekki Street,Dolphin Estate" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<div class="form-group__title"><span>City</span></div>
						<div class="form-group__container">
							<select name="country_id" title="Country" class="form-control validate-select">
								<option value="BH">Bahrain</option>
								<option value="BD">Bangladesh</option>
								<option value="BB">Barbados</option>
								<option value="BY">Belarus</option>
							</select>
						</div>
					</div>
					<div class="form-group">
					  <div class="form-group__title"><span>Area</span></div>
					  <div class="form-group__container">
						<select name="country_id" title="Country" class="form-control validate-select">
						  <option value="BH">Bahrain</option>
						  <option value="BD">Bangladesh</option>
						  <option value="BB">Barbados</option>
						  <option value="BY">Belarus</option>
						</select>
					  </div>
					</div>
					<div class="form-group">
					  <div class="form-group__title"><span>Description</span></div>
					  <div class="form-group__container">
						<textarea placeholder="(optional) e.g. enter through secretariat gate and turn left. Ibeju Lekki street is the third street." class="form-control"></textarea>
					  </div>
					</div>
					<div class="form-group">
					  <div class="form-group__title"><span>Special instructions</span></div>
					  <div class="form-group__container">
						<textarea placeholder="(Optional) e.g. Call my mobile phone when delivery arrives." class="form-control"></textarea>
					  </div>
					</div>
					<div class="buttons-set text-right">
					  <button type="button" class="btn-cancel">Cancel</button>
					  <button data-action="save-customer-address" type="submit" class="btn-save">Save Address</button>
					</div>
				</form>
			</div>*/ ?>
			
			<?php echo $this->getChildHtml('customer_address_edit') ?>
			
			
		</div>
	</div>














<?php /*<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2><?php echo $this->__('Default Addresses') ?></h2>
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
           </li>
        <?php else: ?>
            <li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            </li>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="item">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
            </li>
        <?php else: ?>
            <li class="item empty">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
    <div class="col-2 addresses-additional">
        <h2><?php echo $this->__('Additional Address Entries') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?>
                </address>
                <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>*/ ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this address?')) ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
