<?php /*if($this->getTitle()): ?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php endif;*/ ?>
<?php //echo $this->getMessagesBlock()->toHtml() ?>
<script>
(function($) {
    "use strict";
    $(document).ready(function() {
		$(document).on('click', '#primary_billing', function() {
			var attr = $('#primary_billing').prop('checked');
			$('#primary_shipping').prop('checked', attr);
		});
	});
})(jQuery);
</script>
<?php /* <div class="account-new-btn-wrap">
  <button type="button" class="account-new-btn"><i class="ic-icn-plus-bold"></i><span>New Address</span></button>
</div> */?>
<div class="account-new-form">
	<?php /* <form id="form-validate" action="http://freshtodommot.com/customer/address/formPost/" method="post"> */ ?>
	<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
		<div class="fieldset">
			<?php echo $this->getBlockHtml('formkey')?>
			<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
			<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
		</div>
		<div class="form-group hidden">
			<?php echo $this->getNameBlockHtml() ?>
			
			<div class="form-group__title"><span><?php echo $this->__('Zip/Postal Code') ?></span></div>
			<div class="form-group__container">
				<input type="text" name="postcode" value="-<?php //echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="form-control input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>">
			</div>
			
			<div class="form-group__title"><span><?php echo $this->__('Telephone') ?></span></div>
			<div class="form-group__container">
				<input type="text" name="telephone" value="-<?php //echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" id="telephone" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>">
			</div>
		</div>
		<div class="form-group">
			<div class="form-group__title"><span>Label</span></div>
			<div class="form-group__container">
				<input type="text" name="address_label" value="<?php echo $this->escapeHtml($this->getAddress()->getAddressLabel()); ?>" placeholder="e.g Home" class="form-control">
			</div>
		</div>
		<?php $addressType = $this->escapeHtml($this->getAddress()->getAddressType()); ?>
		<div class="form-group">
			<div class="form-group__title"><span>Address Type</span></div>
			<div class="form-group__container">
				<label class="radio-item"><span class="radio-item__btn">
					<input type="radio" name="address_type" value="1"<?php if($addressType = 1):?> checked="checked"<?php endif; ?>><span></span></span><span class="radio-item__title">Residential</span></label>
				<label class="radio-item"><span class="radio-item__btn">
					<?php ?>
					<input type="radio" name="address_type" value="2"<?php if($addressType = 2):?> checked="checked"<?php endif; ?>><span></span></span><span class="radio-item__title">Non-residential</span></label>
			</div>
		</div>
		
		<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
		<div class="form-group">
			<div class="form-group__title"><span>Street Address</span></div>
			<div class="form-group__container">
				<input type="text" name="street[0]" placeholder="e.g. 8, Ibeju Lekki Street,Dolphin Estate" 
				value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" 
					id="street_1"
					class="input-text form-control required-entry<?php //echo $_streetValidationClass ?>" />
			</div>
		</div>
		
		<div class="form-group">
			<div class="form-group__title"><span>Flat №</span></div>
			<div class="form-group__container">
				<input type="text" name="street[1]" placeholder="(optional) e.g Flat 15"
					value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(2)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
					id="street_2" class="input-text form-control <?php //echo $_streetValidationClass ?>" />
			</div>
		</div>
		
		
		
		<div class="form-group">
			<div class="form-group__title"><span><?php echo $this->__('City') ?></span></div>
			<div class="form-group__container">
				<input type="text" name="city" 
					value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" 
					id="city" class="input-text form-control required-entry<?php //echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" />
			</div>
		</div>

		<div class="form-group">
			<?php /*<label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>*/ ?>
			<div class="form-group__title"><span><?php echo $this->__('State') ?></span></div>
			<div class="input-box">
				<select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select form-control required-entry" style="display:none;">
				   <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				</select>
				<script>
				//<![CDATA[
					$('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
				//]]>
				</script>
				<input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  
					title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" 
					class="input-text form-control required-entry<?php //echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
			</div>
		</div>
		
		<div class="form-group">
			<div class="form-group__title"><span>Country</span></div>
			<div class="form-group__container">
				<?php echo $this->getCountryHtmlSelect() ?>
			</div>
		</div>
		<div class="form-group">
			<div class="form-group__title"><span>Description</span></div>
			<div class="form-group__container">
				<textarea name="address_description" placeholder="(optional) e.g. enter through secretariat gate and turn left. Ibeju Lekki street is the third street." class="form-control"></textarea>
			</div>
		</div>
		<div class="form-group">
			<div class="form-group__title"><span>Special instructions</span></div>
			<div class="form-group__container">
				<textarea name="address_instruction" placeholder="(Optional) e.g. Call my mobile phone when delivery arrives." class="form-control"></textarea>
			</div>
		</div>
		
		<?php $redirect = $this->getRequest()->getParam('redirect')?>
		<li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
			<?php if($this->isDefaultBilling()): ?>
				<strong><?php echo $this->__('Default Address') ?></strong>
			<?php elseif($this->canSetAsDefaultBilling()): ?>
				<input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Address')) ?>" <?php if($redirect): echo 'checked="checked"'; endif;?> /><?php //class="checkbox" ?>
				<input style="display:none;" type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Address')) ?>" <?php if($redirect): echo 'checked="checked"'; endif;?> /><?php //class="checkbox" ?>
					<label for="primary_shipping"><?php echo $this->__('Use as default address') ?></label>
			<?php else: ?>
				<input type="hidden" name="default_billing" value="1" />
				<input type="hidden" name="default_shipping" value="1" />
			<?php endif; ?>
		</li>
		
		<?php if($redirect):?>
			<input type="hidden" name="redirect" value="<?php echo $redirect ?>" />
		<?php endif; ?>
		
		<div class="buttons-set text-right">
			<button onclick="window.document.location.href = '<?php echo $this->escapeUrl($this->getBackUrl()) ?>'" type="button" class="btn-cancel"><?php echo $this->__('Reset') ?></button>
			<button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button btn-save">
				<span><span><?php echo $this->__('Save Address') ?></span></span>
			</button>
		</div>
	</form>
</div>




<?php /*<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <li class="wide">
                <label for="company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" name="company" id="company" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                    </div>
                </div>
                <div class="field">
                    <label for="fax"><?php echo $this->__('Fax') ?></label>
                    <div class="input-box">
                        <input type="text" name="fax" id="fax" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <li class="wide">
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
        <?php endfor; ?>
            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <li class="wide">
                <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                <div class="input-box">
                    <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </li>
            <?php endif; ?>
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" />
					<input style="" type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" />
						<label for="primary_shipping"><?php echo $this->__('Use as default address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
					<input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
</form>*/ ?>
<script>
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>

jQuery('#country').addClass('form-control').addClass('required-entry');
</script>
